# Generated by Django 3.1.3 on 2020-12-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_information',
            old_name='ban_type',
            new_name='ban_type_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='engine',
            new_name='engine_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='fuel_type',
            new_name='fuel_type_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='gearbox',
            new_name='gearbox_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='marka',
            new_name='marka_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='transmission',
            new_name='transmission_id',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='year',
            new_name='year_id',
        ),
    ]
