# Generated by Django 3.1.3 on 2020-12-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_auto_20201206_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_information',
            old_name='ban_type_id',
            new_name='ban_type',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='engine_id',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='fuel_type_id',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='gearbox_id',
            new_name='gearbox',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='marka_id',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='transmission_id',
            new_name='transmission',
        ),
        migrations.RenameField(
            model_name='car_information',
            old_name='year_id',
            new_name='year',
        ),
    ]
