# Generated by Django 3.1.4 on 2020-12-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_auto_20201207_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_information',
            name='ban_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.transmissionbantype'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.yearengine'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.bantypefueltype'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='gearbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.enginegearbox'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.marka'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.markamodel'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.gearboxtransmission'),
        ),
        migrations.AlterField(
            model_name='car_information',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.modelyear'),
        ),
    ]
