# Generated by Django 3.1.4 on 2020-12-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_auto_20201207_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_information',
            name='ban_type',
        ),
        migrations.RemoveField(
            model_name='car_information',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car_information',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car_information',
            name='used_by_km',
        ),
    ]
