# Generated by Django 3.1.4 on 2020-12-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0009_car_information_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_information',
            name='engine',
        ),
    ]
