# Generated by Django 3.1.4 on 2020-12-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0010_remove_car_information_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_information',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.yearengine'),
        ),
    ]
