# Generated by Django 3.1.4 on 2020-12-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0012_remove_car_information_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_information',
            name='year',
        ),
    ]
