# Generated by Django 3.1.4 on 2020-12-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0013_remove_car_information_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_information',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.yearengine'),
        ),
        migrations.AddField(
            model_name='car_information',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.modelyear'),
        ),
    ]
