# Generated by Django 3.1.4 on 2020-12-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0014_auto_20201208_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_filtering_logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.yearengine')),
                ('marka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.marka')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.markamodel')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.modelyear')),
            ],
        ),
    ]
