# Generated by Django 3.1.4 on 2020-12-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0015_car_filtering_logs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='markamodel',
            table='test',
        ),
    ]
